// <auto-generated />
namespace PlayerCRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Intitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intitial));
        
        string IMigrationMetadata.Id
        {
            get { return "202411131039007_Intitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
